nodeLinker: node-modules
enableColors: true
enableProgressBars: true

npmRegistryServer: "https://registry.npmmirror.com"
unsafeHttpWhitelist:
  - "registry.npmmirror.com"

packageExtensions:
  vue@*:
    dependencies:
      vue-template-compiler: "*" 